"""Domain models package for KoreX."""

from packages.domain.models.base import Base, RevisionMixin, TenantScopedMixin, TimestampMixin, utc_now
from packages.domain.models.entities import (
    AttendanceRecord,
    AuditRecord,
    ChangeProposal,
    DependencyEdge,
    Escalation,
    Event,
    Incident,
    KnowledgeItem,
    Notification,
    Participant,
    Resource,
    Route,
    Session,
    Task,
    Vehicle,
    Venue,
    WeatherSignal,
)

__all__ = [
    "Base",
    "TimestampMixin",
    "RevisionMixin",
    "TenantScopedMixin",
    "utc_now",
    "Event",
    "Venue",
    "Session",
    "Participant",
    "Resource",
    "Vehicle",
    "Route",
    "Task",
    "Notification",
    "AttendanceRecord",
    "WeatherSignal",
    "ChangeProposal",
    "DependencyEdge",
    "Incident",
    "Escalation",
    "KnowledgeItem",
    "AuditRecord",
]
